apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-{{ .Values.environment }}
  namespace: {{ .Values.app.namespace }}
data:
{{- $Configs := printf "configs/%s/*" .Values.environment }}
{{ range $path, $bytes := .Files.Glob $Configs }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4}}
{{ end }}