apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.app.name }}-{{ .Values.environment }}
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.listenPort }}
      targetPort: {{ .Values.app.listenPort }}
      protocol: {{ .Values.app.listenProtocol }}
  selector:
    app: {{ .Values.app.name }}